version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db
      
volumes:
  db_data: